"""
Create 100 Analyst Seed Examples

Generates business reasoning tasks for Analyst agent training.
"""

import json
import logging
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


class SeedGenerator:
    """
    Generate 100 seed examples for Analyst agent
    
    Focus: Business reasoning tasks
    """
    
    def __init__(self, output_file: str = "data/socratic_zero/analyst_seeds.jsonl"):
        """
        Initialize seed generator
        
        Args:
            output_file: Path to output JSONL file
        """
        self.output_file = Path(output_file)
        self.output_file.parent.mkdir(parents=True, exist_ok=True)
        
    def generate_seeds(self) -> List[Dict[str, Any]]:
        """
        Generate 100 seed examples
        
        Returns:
            List of seed examples
        """
        seeds = []
        
        # Categories: Financial Analysis, Market Analysis, Strategy, Operations, Risk Assessment
        categories = [
            {
                "name": "Financial Analysis",
                "count": 25,
                "topics": ["Revenue analysis", "Cost optimization", "Profit margins", "Cash flow", "Budget planning"]
            },
            {
                "name": "Market Analysis",
                "count": 25,
                "topics": ["Market size", "Competitive analysis", "Customer segmentation", "Pricing strategy", "Market trends"]
            },
            {
                "name": "Strategy",
                "count": 20,
                "topics": ["Strategic planning", "SWOT analysis", "Growth strategies", "Market entry", "Portfolio optimization"]
            },
            {
                "name": "Operations",
                "count": 15,
                "topics": ["Process optimization", "Supply chain", "Resource allocation", "Efficiency metrics", "Quality control"]
            },
            {
                "name": "Risk Assessment",
                "count": 15,
                "topics": ["Risk analysis", "Compliance", "Financial risk", "Operational risk", "Market risk"]
            }
        ]
        
        example_id = 1
        
        for category in categories:
            for i in range(category["count"]):
                topic = category["topics"][i % len(category["topics"])]
                
                # Generate seed example
                seed = {
                    "id": f"seed_{example_id:03d}",
                    "category": category["name"],
                    "topic": topic,
                    "difficulty": self._assign_difficulty(example_id),
                    "instruction": self._generate_instruction(category["name"], topic),
                    "input": self._generate_input(category["name"], topic),
                    "output": "",  # Will be generated by Solver agent
                    "reasoning": "",  # Will be generated by Solver agent
                    "created_at": datetime.now(timezone.utc).isoformat(),
                    "source": "seed_generator"
                }
                
                seeds.append(seed)
                example_id += 1
        
        logger.info(f"Generated {len(seeds)} seed examples")
        return seeds
    
    def _assign_difficulty(self, example_id: int) -> str:
        """
        Assign difficulty level based on example ID
        
        Returns:
            Difficulty level: "easy", "medium", "hard"
        """
        # Distribute: 40% easy, 40% medium, 20% hard
        if example_id <= 40:
            return "easy"
        elif example_id <= 80:
            return "medium"
        else:
            return "hard"
    
    def _generate_instruction(self, category: str, topic: str) -> str:
        """
        Generate instruction for business reasoning task
        
        Args:
            category: Category name
            topic: Topic name
        
        Returns:
            Instruction string
        """
        templates = {
            "Financial Analysis": [
                f"Analyze the {topic.lower()} for the given scenario and provide recommendations.",
                f"Calculate and interpret {topic.lower()} metrics based on the provided data.",
                f"Evaluate the {topic.lower()} and identify key insights for decision-making.",
            ],
            "Market Analysis": [
                f"Conduct a {topic.lower()} and identify opportunities and threats.",
                f"Analyze {topic.lower()} trends and provide strategic recommendations.",
                f"Evaluate the {topic.lower()} landscape and competitive positioning.",
            ],
            "Strategy": [
                f"Develop a strategic plan for {topic.lower()} based on the context provided.",
                f"Perform {topic.lower()} and recommend strategic actions.",
                f"Analyze the situation and formulate a {topic.lower()} strategy.",
            ],
            "Operations": [
                f"Optimize {topic.lower()} processes based on the given parameters.",
                f"Analyze {topic.lower()} efficiency and recommend improvements.",
                f"Evaluate {topic.lower()} and identify optimization opportunities.",
            ],
            "Risk Assessment": [
                f"Assess {topic.lower()} and identify potential risks and mitigation strategies.",
                f"Analyze {topic.lower()} and evaluate risk exposure.",
                f"Conduct {topic.lower()} and provide risk management recommendations.",
            ]
        }
        
        import random
        template = random.choice(templates.get(category, templates["Financial Analysis"]))
        return template
    
    def _generate_input(self, category: str, topic: str) -> str:
        """
        Generate input scenario for business reasoning task
        
        Args:
            category: Category name
            topic: Topic name
        
        Returns:
            Input scenario string
        """
        scenarios = {
            "Financial Analysis": [
                "A tech startup with $5M annual revenue is evaluating expansion into a new market. Current profit margin is 15%, and they have $2M in cash reserves.",
                "A retail chain with 50 stores is analyzing store profitability. Top 20% of stores generate 60% of revenue, while bottom 30% are unprofitable.",
                "A SaaS company with 10,000 customers is reviewing pricing strategy. Current ARPU is $50/month, churn rate is 5% monthly, and CAC is $200.",
            ],
            "Market Analysis": [
                "A B2B software company is entering a new vertical market worth $500M. Current market leader has 40% share, and there are 3 major competitors.",
                "An e-commerce platform is analyzing customer segments. 80% of revenue comes from 20% of customers, and there's a growing mobile-first segment.",
                "A healthcare startup is evaluating market opportunity in telemedicine. Market is growing 25% annually, and regulatory changes favor remote care.",
            ],
            "Strategy": [
                "A manufacturing company is considering vertical integration. They currently outsource key components, but a supplier acquisition opportunity exists.",
                "A fintech startup is deciding between B2B and B2C focus. B2B has higher margins but longer sales cycles; B2C has volume but lower margins.",
                "A media company is evaluating content strategy. Organic growth is slowing, and they're considering M&A to expand into new genres.",
            ],
            "Operations": [
                "A logistics company is optimizing delivery routes. Current average delivery time is 48 hours, and fuel costs are 30% of operating expenses.",
                "A manufacturing plant is analyzing production efficiency. Current utilization is 70%, defect rate is 2%, and changeover time averages 4 hours.",
                "A service company is reviewing resource allocation. 40% of projects are delayed, and teams are 80% utilized on average.",
            ],
            "Risk Assessment": [
                "A financial services company is assessing compliance risks. New regulations require additional reporting, and current systems may need upgrades.",
                "A supply chain manager is evaluating supplier risk. 60% of components come from a single region, and geopolitical tensions are increasing.",
                "An investment firm is analyzing portfolio risk. Current exposure is 40% equity, 40% fixed income, 20% alternatives, with 15% international allocation.",
            ]
        }
        
        import random
        scenario = random.choice(scenarios.get(category, scenarios["Financial Analysis"]))
        return scenario
    
    def save_seeds(self, seeds: List[Dict[str, Any]]):
        """
        Save seed examples to JSONL file
        
        Args:
            seeds: List of seed examples
        """
        with open(self.output_file, 'w') as f:
            for seed in seeds:
                f.write(json.dumps(seed) + '\n')
        
        logger.info(f"Saved {len(seeds)} seed examples to {self.output_file}")
        print(f"✅ Saved {len(seeds)} seed examples to {self.output_file}")


def main():
    """Generate and save 100 seed examples"""
    generator = SeedGenerator()
    seeds = generator.generate_seeds()
    generator.save_seeds(seeds)
    
    print(f"\n✅ Generated {len(seeds)} Analyst seed examples")
    print(f"   Categories: Financial Analysis (25), Market Analysis (25), Strategy (20), Operations (15), Risk Assessment (15)")
    print(f"   Difficulty: Easy (40), Medium (40), Hard (20)")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
